package org.ejercicioDeMatricez.gui;

import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class App extends javax.swing.JFrame {
        
    DefaultTableModel model1;
    DefaultTableModel model2;
    DefaultTableModel model3;
    
    public App() {
        
        initComponents();
        this.setLocationRelativeTo(null);
//        TableModel tableModel = tableSMatriz1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlAdicion = new javax.swing.JPanel();
        sc1 = new javax.swing.JScrollPane();
        tableSMatriz1 = new javax.swing.JTable();
        sc2 = new javax.swing.JScrollPane();
        tableSMatriz2 = new javax.swing.JTable();
        sc3 = new javax.swing.JScrollPane();
        tableSMatriz3 = new javax.swing.JTable();
        txtSColum = new javax.swing.JTextField();
        txtSFilas = new javax.swing.JTextField();
        btnAsignarS = new javax.swing.JButton();
        btnCalcularSuma = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlResta = new javax.swing.JPanel();
        pnlSustraccion1 = new javax.swing.JPanel();
        sc4 = new javax.swing.JScrollPane();
        tableRMatriz1 = new javax.swing.JTable();
        sc5 = new javax.swing.JScrollPane();
        tableRMatriz2 = new javax.swing.JTable();
        sc6 = new javax.swing.JScrollPane();
        tableRMatriz3 = new javax.swing.JTable();
        txtRColum = new javax.swing.JTextField();
        txtRFilas = new javax.swing.JTextField();
        btnAsignarR = new javax.swing.JButton();
        btnCalcularResta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlMulti = new javax.swing.JPanel();
        pnlAdicion2 = new javax.swing.JPanel();
        sc7 = new javax.swing.JScrollPane();
        tableMMatriz1 = new javax.swing.JTable();
        sc8 = new javax.swing.JScrollPane();
        tableMMatriz2 = new javax.swing.JTable();
        sc9 = new javax.swing.JScrollPane();
        tableMMatriz3 = new javax.swing.JTable();
        btnAsignarM = new javax.swing.JButton();
        btnCalcularMultiplicacion = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtMFilas1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtMColumFila = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtMColum2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        pnlDetermin = new javax.swing.JPanel();
        pnlAdicion3 = new javax.swing.JPanel();
        sc10 = new javax.swing.JScrollPane();
        tableDMatriz = new javax.swing.JTable();
        btnCalcularD = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btnDMatrizO2 = new javax.swing.JButton();
        btnDMatrizO3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        lblResultadoDeterminante = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tableSMatriz1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        sc1.setViewportView(tableSMatriz1);

        tableSMatriz2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        sc2.setViewportView(tableSMatriz2);

        tableSMatriz3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        sc3.setViewportView(tableSMatriz3);

        btnAsignarS.setText("Asignar Matriz");
        btnAsignarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarSActionPerformed(evt);
            }
        });

        btnCalcularSuma.setText("Calcular");
        btnCalcularSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularSumaActionPerformed(evt);
            }
        });

        jLabel1.setText("Columnas");

        jLabel2.setText("Filas");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3.setText("+");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4.setText("=");

        javax.swing.GroupLayout pnlAdicionLayout = new javax.swing.GroupLayout(pnlAdicion);
        pnlAdicion.setLayout(pnlAdicionLayout);
        pnlAdicionLayout.setHorizontalGroup(
            pnlAdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdicionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdicionLayout.createSequentialGroup()
                        .addGroup(pnlAdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSColum, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAsignarS)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalcularSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAdicionLayout.createSequentialGroup()
                        .addComponent(sc1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(sc2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sc3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnlAdicionLayout.setVerticalGroup(
            pnlAdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdicionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlAdicionLayout.createSequentialGroup()
                        .addGroup(pnlAdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtSColum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAsignarS)
                    .addComponent(btnCalcularSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnlAdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdicionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlAdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sc2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sc1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sc3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlAdicionLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel3))
                    .addGroup(pnlAdicionLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel4)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Adición", pnlAdicion);

        tableRMatriz1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        sc4.setViewportView(tableRMatriz1);

        tableRMatriz2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        sc5.setViewportView(tableRMatriz2);

        tableRMatriz3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        tableRMatriz3.setEnabled(false);
        sc6.setViewportView(tableRMatriz3);

        btnAsignarR.setText("Asignar Matriz");
        btnAsignarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarRActionPerformed(evt);
            }
        });

        btnCalcularResta.setText("Calcular");
        btnCalcularResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularRestaActionPerformed(evt);
            }
        });

        jLabel5.setText("Columnas");

        jLabel6.setText("Filas");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 50)); // NOI18N
        jLabel7.setText("-");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel8.setText("=");

        javax.swing.GroupLayout pnlSustraccion1Layout = new javax.swing.GroupLayout(pnlSustraccion1);
        pnlSustraccion1.setLayout(pnlSustraccion1Layout);
        pnlSustraccion1Layout.setHorizontalGroup(
            pnlSustraccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSustraccion1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSustraccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlSustraccion1Layout.createSequentialGroup()
                        .addGroup(pnlSustraccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSustraccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRColum, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(txtRFilas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAsignarR)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalcularResta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlSustraccion1Layout.createSequentialGroup()
                        .addComponent(sc4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sc5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sc6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSustraccion1Layout.setVerticalGroup(
            pnlSustraccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSustraccion1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSustraccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlSustraccion1Layout.createSequentialGroup()
                        .addGroup(pnlSustraccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtRColum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSustraccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtRFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAsignarR)
                    .addComponent(btnCalcularResta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnlSustraccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSustraccion1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(pnlSustraccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)))
                    .addGroup(pnlSustraccion1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlSustraccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sc5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sc4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sc6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRestaLayout = new javax.swing.GroupLayout(pnlResta);
        pnlResta.setLayout(pnlRestaLayout);
        pnlRestaLayout.setHorizontalGroup(
            pnlRestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRestaLayout.createSequentialGroup()
                .addComponent(pnlSustraccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        pnlRestaLayout.setVerticalGroup(
            pnlRestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRestaLayout.createSequentialGroup()
                .addComponent(pnlSustraccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sustracción", pnlResta);

        tableMMatriz1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        sc7.setViewportView(tableMMatriz1);

        tableMMatriz2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        sc8.setViewportView(tableMMatriz2);

        tableMMatriz3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        tableMMatriz3.setEnabled(false);
        sc9.setViewportView(tableMMatriz3);

        btnAsignarM.setText("Asignar Matrices");
        btnAsignarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarMActionPerformed(evt);
            }
        });

        btnCalcularMultiplicacion.setText("Calcular");
        btnCalcularMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularMultiplicacionActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel11.setText("x");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel12.setText("=");

        jLabel9.setText("Columnas");

        jLabel10.setText("Filas");

        jLabel15.setText("Matriz 1");

        jLabel13.setText("Filas");

        jLabel18.setText("Matriz 2");

        jLabel14.setText("Columnas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMColum2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)))
                            .addComponent(jLabel18)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtMFilas1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMColumFila)
                        .addGap(75, 75, 75)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMFilas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMColumFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMColum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout pnlAdicion2Layout = new javax.swing.GroupLayout(pnlAdicion2);
        pnlAdicion2.setLayout(pnlAdicion2Layout);
        pnlAdicion2Layout.setHorizontalGroup(
            pnlAdicion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdicion2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdicion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdicion2Layout.createSequentialGroup()
                        .addComponent(sc7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sc8, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAdicion2Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAsignarM)))
                .addGap(12, 12, 12)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAdicion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCalcularMultiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sc9, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAdicion2Layout.setVerticalGroup(
            pnlAdicion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdicion2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pnlAdicion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdicion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAsignarM)
                        .addComponent(btnCalcularMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(pnlAdicion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdicion2Layout.createSequentialGroup()
                        .addGroup(pnlAdicion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAdicion2Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel11))
                            .addComponent(sc8, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sc7, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sc9, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdicion2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(79, 79, 79))))
        );

        javax.swing.GroupLayout pnlMultiLayout = new javax.swing.GroupLayout(pnlMulti);
        pnlMulti.setLayout(pnlMultiLayout);
        pnlMultiLayout.setHorizontalGroup(
            pnlMultiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMultiLayout.createSequentialGroup()
                .addComponent(pnlAdicion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        pnlMultiLayout.setVerticalGroup(
            pnlMultiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMultiLayout.createSequentialGroup()
                .addComponent(pnlAdicion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Multiplicación", pnlMulti);

        tableDMatriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        sc10.setViewportView(tableDMatriz);

        btnCalcularD.setText("Calcular Det 2x2");
        btnCalcularD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularDActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel16.setText("=");

        btnDMatrizO2.setText("Matriz de orden 2");
        btnDMatrizO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDMatrizO2ActionPerformed(evt);
            }
        });

        btnDMatrizO3.setText("Matriz de orden 3");
        btnDMatrizO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDMatrizO3ActionPerformed(evt);
            }
        });

        jLabel17.setText("Determinante");

        lblResultadoDeterminante.setBackground(new java.awt.Color(255, 0, 102));
        lblResultadoDeterminante.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblResultadoDeterminante.setAutoscrolls(true);

        jButton1.setText("Calcular Det 3x3");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdicion3Layout = new javax.swing.GroupLayout(pnlAdicion3);
        pnlAdicion3.setLayout(pnlAdicion3Layout);
        pnlAdicion3Layout.setHorizontalGroup(
            pnlAdicion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdicion3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdicion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlAdicion3Layout.createSequentialGroup()
                        .addComponent(sc10, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17))
                    .addGroup(pnlAdicion3Layout.createSequentialGroup()
                        .addGroup(pnlAdicion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDMatrizO2)
                            .addComponent(btnDMatrizO3))
                        .addGap(70, 70, 70)
                        .addGroup(pnlAdicion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlAdicion3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblResultadoDeterminante, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCalcularD, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        pnlAdicion3Layout.setVerticalGroup(
            pnlAdicion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdicion3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdicion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCalcularD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDMatrizO2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAdicion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDMatrizO3)
                    .addComponent(jButton1))
                .addGap(12, 12, 12)
                .addGroup(pnlAdicion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdicion3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(21, 21, 21)
                        .addGroup(pnlAdicion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(lblResultadoDeterminante, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(sc10, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDeterminLayout = new javax.swing.GroupLayout(pnlDetermin);
        pnlDetermin.setLayout(pnlDeterminLayout);
        pnlDeterminLayout.setHorizontalGroup(
            pnlDeterminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
            .addGroup(pnlDeterminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlDeterminLayout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(pnlAdicion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 7, Short.MAX_VALUE)))
        );
        pnlDeterminLayout.setVerticalGroup(
            pnlDeterminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
            .addGroup(pnlDeterminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlDeterminLayout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(pnlAdicion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Determinante(2/3)", pnlDetermin);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarSActionPerformed

        this.model1 = (DefaultTableModel) tableSMatriz1.getModel();
        this.model2 = (DefaultTableModel) tableSMatriz2.getModel();
        this.model3 = (DefaultTableModel) tableSMatriz3.getModel();
        
        int colum = Integer.parseInt(txtSColum.getText());
        int filas = Integer.parseInt(txtSFilas.getText());
        
        this.asignarTamanio(model1,filas,colum);
        this.asignarTamanio(model2,filas,colum);
        this.asignarTamanio(model3,filas,colum);
        
    }//GEN-LAST:event_btnAsignarSActionPerformed

    private void btnCalcularSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularSumaActionPerformed
        HiloCalculo hilo = new HiloCalculo();
        hilo.run(1);
        hilo.stop();
    }//GEN-LAST:event_btnCalcularSumaActionPerformed

    private void btnAsignarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarRActionPerformed
        this.model1 = (DefaultTableModel) tableRMatriz1.getModel();
        this.model2 = (DefaultTableModel) tableRMatriz2.getModel();
        this.model3 = (DefaultTableModel) tableRMatriz3.getModel();
        
        int colum = Integer.parseInt(txtRColum.getText());
        int filas = Integer.parseInt(txtRFilas.getText());
        
        this.asignarTamanio(model1,filas,colum);
        this.asignarTamanio(model2,filas,colum);
        this.asignarTamanio(model3,filas,colum);
        
    }//GEN-LAST:event_btnAsignarRActionPerformed

    private void btnAsignarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarMActionPerformed
        this.model1 = (DefaultTableModel) tableMMatriz1.getModel();
        this.model2 = (DefaultTableModel) tableMMatriz2.getModel();
        this.model3 = (DefaultTableModel) tableMMatriz3.getModel();
        
        int filas1 = Integer.parseInt(txtMFilas1.getText());
        int colum1 = Integer.parseInt(txtMColumFila.getText());
        
        int filas2 = Integer.parseInt(txtMColumFila.getText());
        int colum2 = Integer.parseInt(txtMColum2.getText());
        
        asignarTamanio(model1, filas1, colum1);
        asignarTamanio(model2, filas2, colum2);
        asignarTamanio(model3, filas1, colum2);
        
        
        
        
    }//GEN-LAST:event_btnAsignarMActionPerformed

    private void btnCalcularRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularRestaActionPerformed
        HiloCalculo hiloResta = new HiloCalculo();
        hiloResta.run(2);
        hiloResta.stop();
    }//GEN-LAST:event_btnCalcularRestaActionPerformed

    private void btnCalcularMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularMultiplicacionActionPerformed
        HiloCalculo hMult = new HiloCalculo();
        hMult.run(3);
        hMult.stop();
        
    }//GEN-LAST:event_btnCalcularMultiplicacionActionPerformed

    private void btnDMatrizO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDMatrizO2ActionPerformed
        this.model1 = (DefaultTableModel) tableDMatriz.getModel();
        this.asignarTamanio(model1, 2, 2);
    }//GEN-LAST:event_btnDMatrizO2ActionPerformed

    private void btnDMatrizO3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDMatrizO3ActionPerformed
        this.model1 = (DefaultTableModel) tableDMatriz.getModel();
        this.asignarTamanio(model1, 3, 3);
    }//GEN-LAST:event_btnDMatrizO3ActionPerformed

    private void btnCalcularDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularDActionPerformed
        HiloDeterminante hiloDet = new HiloDeterminante();
        hiloDet.det2();
    }//GEN-LAST:event_btnCalcularDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HiloDeterminante hiloDet3 = new HiloDeterminante();
        hiloDet3.det3();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarM;
    private javax.swing.JButton btnAsignarR;
    private javax.swing.JButton btnAsignarS;
    private javax.swing.JButton btnCalcularD;
    private javax.swing.JButton btnCalcularMultiplicacion;
    private javax.swing.JButton btnCalcularResta;
    private javax.swing.JButton btnCalcularSuma;
    private javax.swing.JButton btnDMatrizO2;
    private javax.swing.JButton btnDMatrizO3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblResultadoDeterminante;
    private javax.swing.JPanel pnlAdicion;
    private javax.swing.JPanel pnlAdicion2;
    private javax.swing.JPanel pnlAdicion3;
    private javax.swing.JPanel pnlDetermin;
    private javax.swing.JPanel pnlMulti;
    private javax.swing.JPanel pnlResta;
    private javax.swing.JPanel pnlSustraccion1;
    private javax.swing.JScrollPane sc1;
    private javax.swing.JScrollPane sc10;
    private javax.swing.JScrollPane sc2;
    private javax.swing.JScrollPane sc3;
    private javax.swing.JScrollPane sc4;
    private javax.swing.JScrollPane sc5;
    private javax.swing.JScrollPane sc6;
    private javax.swing.JScrollPane sc7;
    private javax.swing.JScrollPane sc8;
    private javax.swing.JScrollPane sc9;
    private javax.swing.JTable tableDMatriz;
    private javax.swing.JTable tableMMatriz1;
    private javax.swing.JTable tableMMatriz2;
    private javax.swing.JTable tableMMatriz3;
    private javax.swing.JTable tableRMatriz1;
    private javax.swing.JTable tableRMatriz2;
    private javax.swing.JTable tableRMatriz3;
    private javax.swing.JTable tableSMatriz1;
    private javax.swing.JTable tableSMatriz2;
    private javax.swing.JTable tableSMatriz3;
    private javax.swing.JTextField txtMColum2;
    private javax.swing.JTextField txtMColumFila;
    private javax.swing.JTextField txtMFilas1;
    private javax.swing.JTextField txtRColum;
    private javax.swing.JTextField txtRFilas;
    private javax.swing.JTextField txtSColum;
    private javax.swing.JTextField txtSFilas;
    // End of variables declaration//GEN-END:variables
    
    private void asignarTamanio(DefaultTableModel model,int filas, int colum){
        model.setRowCount(filas);
        model.setColumnCount(colum);
    }    
    
    private class HiloCalculo extends Thread{
        int colum = model1.getColumnCount();
        int filas = model1.getRowCount() ;
        
        public void run(int op){
            if(op == 1 || op ==2){
                for(Integer i=0 ; i<filas ; i++){
                    for(Integer j = 0; j < colum; j++){
                        if(op == 1){
                            Integer valorS1 = Integer.parseInt((String) model1.getValueAt(i,j));
                            Integer valorS2 = Integer.parseInt((String) model2.getValueAt(i,j));
                            model3.setValueAt((valorS1+valorS2), i, j);                   
                        }else {
                            Integer valorR1 = Integer.parseInt((String) model1.getValueAt(i,j));
                            Integer valorR2 = Integer.parseInt((String) model2.getValueAt(i,j));
                            model3.setValueAt((valorR1-valorR2), i, j);
                        }
                    }
                }
            }else{
                int c1 = model1.getColumnCount();
                int f2 = model2.getRowCount();
                
                
                if(op == 3){
                    for (int i = 0; i < model1.getRowCount(); i++) {
                        for (int j = 0; j < model2.getColumnCount(); j++) {
                            int acumulador = 0;
                            for (int k = 0; k < model1.getColumnCount(); k++) {
                                
                                // aquí se multiplica la matriz
                                int valor1 =  Integer.parseInt((String) model1.getValueAt(i,k));
                                int valor2 =  Integer.parseInt((String) model2.getValueAt(k,j));
                                int producto = valor1 * valor2;
                                acumulador += producto;
                            }
                            model3.setValueAt(acumulador, i, j);
                        }
                    }

                }
            }
        }
    }
    
    public class HiloDeterminante extends Thread {
        public void det2(){
            int val1 = Integer.parseInt((String) model1.getValueAt(0, 0));
            int val2 = Integer.parseInt((String) model1.getValueAt(1, 1));
            int val3 = Integer.parseInt((String) model1.getValueAt(1, 0));
            int val4 = Integer.parseInt((String) model1.getValueAt(0, 1));
            int det = val1*val2 - val3 * val4; 
            lblResultadoDeterminante.setText(Integer.toString(det));
        }
        public void det3(){
            int elemento11 = Integer.parseInt((String) model1.getValueAt(0, 0));
            int elemento12 = Integer.parseInt((String) model1.getValueAt(0, 1));
            int elemento13 = Integer.parseInt((String) model1.getValueAt(0, 2));
            int elemento21 = Integer.parseInt((String) model1.getValueAt(1, 0));
            int elemento22 = Integer.parseInt((String) model1.getValueAt(1, 1));
            int elemento23 = Integer.parseInt((String) model1.getValueAt(1, 2));
            int elemento31 = Integer.parseInt((String) model1.getValueAt(2, 0));
            int elemento32 = Integer.parseInt((String) model1.getValueAt(2, 1));
            int elemento33 = Integer.parseInt((String) model1.getValueAt(2, 2));
            
            int det = elemento11 * ((elemento22 * elemento33)-(elemento32*elemento23))-
                      elemento12 * ((elemento21 * elemento33)-(elemento31*elemento23))+
                      elemento13 * ((elemento21 * elemento32)-(elemento31*elemento22));
            lblResultadoDeterminante.setText(Integer.toString(det));
        }
    }
}
